"use client";

interface VisitCardProps {
  traceId: string;
}

export function VisitCard({ traceId: _traceId }: VisitCardProps) {
  // TODO: Fetch trace data from DB, render print-optimized visit card
  return (
    <div className="rounded-xl bg-white p-8 text-gray-900">
      <h1 className="text-xl font-semibold">Visit Card</h1>
      <p className="mt-1 text-sm text-gray-500">
        Generated {new Date().toLocaleDateString()}
      </p>

      <section className="mt-6">
        <h2 className="text-sm font-semibold uppercase tracking-wider text-gray-400">
          Patterns Identified
        </h2>
        {/* TODO: Render chain summary */}
      </section>

      <section className="mt-6">
        <h2 className="text-sm font-semibold uppercase tracking-wider text-gray-400">
          Causal Hypothesis
        </h2>
        {/* TODO: Render primary chain in text form */}
      </section>

      <section className="mt-6">
        <h2 className="text-sm font-semibold uppercase tracking-wider text-gray-400">
          Questions to Discuss
        </h2>
        {/* TODO: Render doctor-flagged suggestions */}
      </section>

      <footer className="mt-8 border-t border-gray-200 pt-4 text-xs text-gray-400">
        Generated by TRACE &middot; Not a diagnosis &mdash; a starting point
        for conversation.
      </footer>
    </div>
  );
}
